Resources:
  FrontendInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0abcdef1234567890  # e.g., Amazon Linux 2
      SecurityGroupIds:
        - sg-123456
      SubnetId: subnet-123456
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install docker -y
          service docker start
          usermod -a -G docker ec2-user
          docker login -u <your-dockerhub-username> -p <your-dockerhub-password>
          docker pull anishsabharwal/nft-marketplace:latest
          docker run -d -p 3000:3000 anishsabharwal/nft-marketplace:latest
